# Generated by Django 3.2.8 on 2021-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quartier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartier',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
